import { StyleSheet } from "react-native";

export const globalStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#EFF0F4",
    alignItems: "center",
    justifyContent: "center",
  },
  inputView: {
    borderRadius: 30,
    width: "100%",
    marginBottom: "4%",
    alignItems: "center",
  },

  TextInput: {
    backgroundColor: "#FFF",
    borderRadius: 30,
    width: "70%",
    minHeight: "15%",
    marginBottom: "5%",
    alignItems: "center",
    fontSize: 17,
  },
  ProfileInput: {
    backgroundColor: "#FFF",
    borderRadius: 30,
    width: "70%",
    minHeight: "7%",
    alignItems: "center",
    fontSize: 17,
  },

  forgot_button: {
    height: 30,
    marginTop: "3%",
  },

  loginBtn: {
    width: "50%",
    borderRadius: 25,
    alignItems: "center",
    justifyContent: "center",
    marginTop: "10%",
    backgroundColor: "#195F6B",
    marginBottom: "20%",
    minHeight: "13%",
  },
  startBtn: {
    width: "50%",
    borderRadius: 25,
    height: "8%",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#195F6B",
    marginBottom: "10%",
  },
  title: {
    fontSize: 45,
    fontWeight: "bold",
  },
  subtitle: {
    fontSize: 35,
    fontWeight: "bold",
  },
  dogName: {
    fontSize: 25,
    marginRight: "auto",
    marginTop: 20,
    marginLeft: 20,
  },
  profileText: {
    marginRight: "auto",
    fontSize: 25,
  },
  logo: {
    width: "100%",
    height: "40%",
  },
  homeBtns: {
    width: "70%",
    borderRadius: 25,
    height: "8%",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginTop: "8%",
    backgroundColor: "#195F6B",
  },
  acceptBtns: {
    width: "45%",
    borderRadius: 25,
    height: 50,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 15,
    backgroundColor: "#195F6B",
    marginLeft: 15,
  },
  editBtn: {
    width: "15%",
    borderRadius: 25,
    height: 30,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#195F6B",
    marginTop: 10,
    marginLeft: "auto",
  },
  pager: {
    height: "50%",
    width: "100%",
    backgroundColor: "#16BAC6",
    borderColor: "#16BAC6",
    borderWidth: 10,
  },
  picture: {
    width: "40%",
    height: "20%",
    marginLeft: "30%",
    marginVertical: "3%",
  },
  pictureDog: {
    width: "33%",
    height: "30%",
    marginBottom: "5%",
  },
  historyDog: {
    width: "33%",
    height: "20%",
    marginBottom: "5%",
    marginHorizontal: "33%",
  },
  tag: {
    fontSize: 20,
    marginHorizontal: "4%",
    backgroundColor: "#195F6B",
    borderRadius: 25,
    width: "30%",
    height: "80%",
    justifyContent: "center",
  },
  historyTag: {
    fontSize: 20,
    backgroundColor: "#195F6B",
    borderRadius: 25,
    width: "40%",
    height: "50%",
    justifyContent: "center",
  },
  tagText: {
    textAlign: "center",
    textAlignVertical: "center",
    color: "#FFFFFF",
  },
  row: {
    flex: 1,
    flexDirection: "row",
    minHeight: "5%",
  },
  ButtonsText: {
    color: "#FFFFFF",
  },
  picturePicker: {
    fontSize: 20,
    backgroundColor: "#195F6B",
    borderRadius: 25,
    width: "60%",
    height: "8%",
    justifyContent: "center",
    alignItems: "center",
    marginLeft: "20%",
  },
  historyText: {
    marginRight: "auto",
    fontSize: 20,
    marginLeft: "5%",
  },
  historyContainer: {
    height: "100%",
    width: "110%",
    backgroundColor: "#EFF0F4",
    alignItems: "center",
    justifyContent: "center",
  },
  navigationBarProfileEdit:{
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    marginTop:"5%",
    marginBottom: "-20%",
  },
  navigationBarHome:{
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    marginTop:"5%",
    marginBottom: "10%",
  },
  navigationBarHistory:{
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    marginTop:"90%",
  },
});
